language: java
jdk:
  - oraclejdk8
  - openjdk8

env:
  ORG_GRADLE_PROJECT_sonatypeUsername=xxx
  ORG_GRADLE_PROJECT_sonatypePassword=xxx

cache:
  directories:
    - $HOME/.gradle

script:
  - ./gradlew build jacocoTestReport

notifications:
  email:
    - sonunitw12@gmail.com

after_success:
  - ./gradlew test jacocoTestReport coveralls
